version: "3.8"

services:
  laravel_app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www   # map local Laravel project into container
    ports:
      - "8000:8000"
    depends_on:
      laravel_db:
        condition: service_healthy
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: laravel_db   # connect via Docker service name
      DB_PORT: 3306         # MySQL internal port
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    networks:
      - laravel_net

  laravel_db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"   # host:container mapping
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - laravel_net

volumes:
  db_data:
  jenkins_home:

networks:
  laravel_net:
    driver: bridge
